### ISSUE TITLE
no waqf/pause mark in the arabic text

### ISSUE THREAD

**Issue by rashnk** [risan/quran-json#6]
Chapter 2:10   ۖ   is missing 

it should display waqf فِي قُلُوبِهِمْ مَرَضٌ فَزَادَهُمُ اللَّهُ مَرَضًا ۖ وَلَهُمْ عَذَابٌ أَلِيمٌ بِمَا كَانُوا يَكْذِبُونَ

Chapter 104:4
after kallaa a waqf is required كَلَّا ۖ لَيُنْبَذَنَّ فِي الْحُطَمَةِ
in the 104.pretty.json no waqf "text": "كَلَّا لَيُنۢبَذَنَّ فِى ٱلْحُطَمَةِ",

**Comment by yousif-hag-ahmed** [comment]
quran text is inconsistent please be very aware because this should not have any mistakes 
for example 
![Correction](https://user-images.githubusercontent.com/69925471/109892164-6a75bf80-7c58-11eb-9a71-f76d5a8cc96b.PNG)

should be 

![correct](https://user-images.githubusercontent.com/69925471/109892834-aad53d80-7c58-11eb-854d-dc27c76a9613.PNG)

please be aware ,thank you for the effort

**Comment by risan** [comment]
Hi, thank you for your concern. 

I have updated the library to use the data from [Al Quran Cloud API](https://alquran.cloud/api).

The latest updates should fix the issue above.

- https://unpkg.com/quran-json@2.0.0/surahs/2.json
- https://unpkg.com/quran-json@2.0.0/surahs/104.json
